
GET http://localhost:8080/api/messages/
Accept: application/json

###

POST http://localhost:8080/api/messages/
Content-Type: application/json

{
  "texte": "Salut"
}

###
GET http://localhost:8080/api/messages/1
Accept: application/json

###
POST http://localhost:8080/api/messages/
Content-Type: application/json

{
  "texte": "ReSalut"
}

###
DELETE http://localhost:8080/api/messages/1
Accept: application/json

###


GET http://localhost:8080/api/messages/
Accept: application/json

###


PATCH http://localhost:8080/api/messages/2
Content-Type: application/json

{
  "texte": "Salut"
}



###
GET http://localhost:8080/api/messages/2
Accept: application/json

###
GET http://localhost:8080/api/messages/
Accept: application/json

###

