GET http://localhost:8080/api/messages
#Accept: application/json

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}
###

POST http://localhost:8080/api/messages
Authorization: Basic Vincent vinc
Content-Type: application/json

{
  "texte": "Salut"
}




###
GET http://localhost:8080/api/messages/1
Authorization: Basic Vincent vinc
Accept: application/json

###
POST http://localhost:8080/api/messages/
Authorization: Basic Vincent vinc
Content-Type: application/json

{
  "texte": "ReSalut"
}

###
DELETE http://localhost:8080/api/messages/2
Authorization: Basic admin admin
Accept: application/json

###


GET http://localhost:8080/api/messages
Accept: application/json

###
POST http://localhost:8080/api/messages/
Authorization: Basic Vincent vinc
Content-Type: application/json

{
  "texte": "Zalut"
}

###

PATCH http://localhost:8080/api/messages/3
Authorization: Basic admin admin
Content-Type: application/json

{
  "texte": "Salut"
}

###

PATCH http://localhost:8080/api/messages/3
Authorization: Basic Vincent vinc
Content-Type: application/json

{
  "texte": "Salut"
}


### DELETED so KO
GET http://localhost:8080/api/messages/2
Authorization: Basic admin admin
Accept: application/json

###
GET http://localhost:8080/api/messages
Accept: application/json

### NOPE

POST http://localhost:8080/api/users
Authorization: Basic Vincent vinc
Content-Type: application/json

{
  "login": "yoyo2",
  "password": "yoyo2",
  "isAdmin": true
}

### Yep

POST http://localhost:8080/api/users
Authorization: Basic admin admin
Content-Type: application/json

{
  "login": "yoyo2",
  "password": "yoyo2",
  "admin": true
}

###
POST http://localhost:8080/api/messages/
Authorization: Basic fred fred
Content-Type: application/json

{
  "texte": "Yo! c'est Yo"
}

###KO


GET http://localhost:8080/api/users/yoyo2
Authorization: Basic admin admin
Content-Type: application/json

###KO
GET http://localhost:8080/api/users/yoyo2
Authorization: Basic fred fred
Content-Type: application/json

###OK

GET http://localhost:8080/api/users/yoyo2
Authorization: Basic yoyo2 yoyo2
Content-Type: application/json

###KO

GET http://localhost:8080/api/users2/yoyo2
Authorization: Basic admin admin
Content-Type: application/json

###KO



GET http://localhost:8080/api/users2/yoyo2
Authorization: Basic fred fred
Content-Type: application/json

###OK

GET http://localhost:8080/api/users2/yoyo2
Authorization: Basic yoyo2 yoyo2
Content-Type: application/json

###




POST http://localhost:8080/api/users
Authorization: Basic admin admin
Content-Type: application/json

{
  "login": "yoyo3",
  "password": "yoyo3",
  "admin": true
}

###KO

GET http://localhost:8080/api/users2/yoyo3
Authorization: Basic fred fred
Content-Type: application/json

###OK

GET http://localhost:8080/api/users2/yoyo3
Authorization: Basic yoyo3 yoyo3
Content-Type: application/json

###

GET http://localhost:8080/api/users/Vincent/messages
Authorization: Basic fred fred
Content-Type: application/json

###

GET http://localhost:8080/api/users
Authorization: Basic fred fred
Content-Type: application/json

###
DELETE http://localhost:8080/api/users/fred
Authorization: Basic fred fred
Content-Type: application/json

###



GET http://localhost:8080/api/messages
Authorization: Basic fred fred
Content-Type: application/json

###
GET http://localhost:8080/api/users
Authorization: Basic fred fred
Content-Type: application/json

###
